{% set name = "fake-useragent" %}
{% set version = "2.0.0" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8b547af788ed7ab018c5f13f67f229d9a4e034afe11fcbb3fa28a380eda68dae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
    - importlib-resources >=6.0  # [py<310]
  run:
    - python >={{ python_min }}
    - importlib-resources >=6.0  # [py<310]

test:
  imports:
    - fake_useragent
  commands:
    - pip check
  requires:
    - python >={{ python_min }}
    - pip

about:
  home: https://github.com/hellysmile/fake-useragent
  summary: Up to date simple useragent faker with real world database
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
