{% set name = "fake-useragent" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fake-useragent-{{ version }}.tar.gz
  sha256: b473a8faa9a94014b7ea8783ca36ea2c119e33a9eee1becd2e44398428b0367f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - fake_useragent
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hellysmile/fake-useragent
  summary: Up to date simple useragent faker with real world database
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
