{% set name = "fake-useragent" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fake-useragent-{{ version }}.tar.gz
  sha256: 0b3a223b4c03e3df46b0e9ff53ad26cf4690f68871396b9c59a7fa6ee830c395

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - fake_useragent
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hellysmile/fake-useragent
  summary: Up to date simple useragent faker with real world database
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
