{% set name = "fake-useragent" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fake-useragent-{{ version }}.tar.gz
  sha256: 5426e4015d8ccc5bb25f64d3dfcfd3915eba30ffebd31b86b60dc7a4c5d65528

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - fake_useragent
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hellysmile/fake-useragent
  summary: Up to date simple useragent faker with real world database
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
